version: 2.1
general:
  branches:
    only:
     - master
     - v1.0
     - v2.0
jobs:
  build-test:
    working_directory: /go/src/github.com/blend/go-sdk
    docker:
    - image: circleci/golang:1.11
    - image: circleci/postgres:9.6.2-alpine
      environment:
        POSTGRES_USER: circleci
        POSTGRES_DB: circleci
    steps:
    - checkout
    - run:
        name: Set the upstream
        command: |
          eval "git branch --set-upstream-to=origin/`git rev-parse --abbrev-ref HEAD` `git rev-parse --abbrev-ref HEAD`"
    - run:
        name: new-install
        command: make new-install
    - run:
        name: ci
        command: make ci
    - store_artifacts:
        path: coverage.html
        destination: coverage.html
  release:
    working_directory: /go/src/github.com/blend/go-sdk
    docker:
    - image: circleci/golang:1.11
    steps:
    - checkout
    - run:
        name: Set the upstream
        command: |
          eval "git branch --set-upstream-to=origin/`git rev-parse --abbrev-ref HEAD` `git rev-parse --abbrev-ref HEAD`"
    - run:
        name: new-install
        command: make new-install
    - run:
        name: tag
        command: make tag push-tag
    - run:
        name: release-all
        command: make release-all
workflows:
  version: 2
  build-test:
     jobs:
      - build-test
  build-test-and-release:
    jobs:
      - build-test
      - approval:
          type: approval
          requires:
            - build-test
      - release:
          requires:
            - approval